### ISSUE TITLE
Provide unit for distance in get_nearest_station

### ISSUE THREAD

**Issue by nuest** [52North/sensorweb4R#2]
Running the example in #1 I don't know if the distance is in meters or ... degrees?

We could to two things:
* add a "[unit]" to the name of the distance variable (which I don't like because a user hast to type that in every time)
* use `?attributes` to set the unit of measurement: `attributes(get_nearest_stations(...)[["distance"]])` would return a list including `uom = m`.

@autermann Your opinion?

**Comment by autermann** [comment]
```r
#' The distance is calculated using computations on an ellipsoid and the
#' returned value is in meters.
```
