### ISSUE TITLE
extend documentation on query methods

### ISSUE THREAD

**Issue by sadriaenssens** [52North/sensorweb4R#32]
Currently not clear from the documentation how you should, for example, select all timeseries of 1 specific station.
Selecting a station within a category works:
```R
srv <- services(endpoint)
cat <- categories(srv)
sta <- stations(srv,category=cat[1])[1]
ts <- timeseries(endpoint, category=cat[1])[1]
```
But this doesn't (no selection on station name is made):
```R
ts <- timeseries(endpoint, station=sta[label(sta)=="BETR802"])
```
How can you select on station, and within that station on pollutant (=phenomona)?

**Comment by autermann** [comment]
It would work exactly like you have tried it, if your endpoint would support it.

This snippet:
```R
timeseries(Endpoint("http://sensorweb.demo.52north.org/sensorwebclient-webapp-stable/api/v1/"),
           service = 'srv_6d9ccea8d609ecb74d4a512922bb7cee',
           station = 'sta_20718c2855f7a486042e8b1e595a8b5e', 
           phenomenon = 'phe_fd0ba6c107e07a2ef448e890cfa5f24a')
```

basically translates to this `GET` request:

<http://sensorweb.demo.52north.org/sensorwebclient-webapp-stable/api/v1/timeseries?service=srv_6d9ccea8d609ecb74d4a512922bb7cee&station=sta_20718c2855f7a486042e8b1e595a8b5e&phenomenon=phe_fd0ba6c107e07a2ef448e890cfa5f24a>

which results in a single timeseries:
```json
[
    {
        "id": "ts_c64ddbe9694d5871ec47444723689925",
        "label": "42101 - CO@BETR802",
        "uom": "Default: ug/m3",
        "station": {
            "properties": {
                "id": "sta_20718c2855f7a486042e8b1e595a8b5e",
                "label": "BETR802"
            },
            "geometry": {
                "coordinates": [
                    4.4307445169709485,
                    51.209266004026645
                ],
                "type": "Point"
            },
            "type": "Feature"
        }
    }
]
```

If you try this with your endpoint, it won't work as your version of the API does not support this filtering. You'll get a list of all timeseries with the specified `Service` and `phenomenon`, the `station` parameter is ignored:

```R
timeseries(Endpoint("http://sosrest.irceline.be/api/v1/"),
           service = 'srv_6d9ccea8d609ecb74d4a512922bb7cee',
           station = 'sta_deaa1541811a3b43279be71bd2cda516', 
           phenomenon = 'phe_fd0ba6c107e07a2ef448e890cfa5f24a')
```

<http://sosrest.irceline.be/api/v1/timeseries?service=srv_6d9ccea8d609ecb74d4a512922bb7cee&station=sta_deaa1541811a3b43279be71bd2cda516&phenomenon=phe_fd0ba6c107e07a2ef448e890cfa5f24a>

I've used the respective identifiers here, but of course you can also use `Phenomenon`, `Service` and `Station` objects to filter the timeseries.

**Comment by opeeters** [comment]
problem is however that the newer REST-api (or rather when deployed directly on the DB) returns "numeric" ID's for timeseries, stations, procedures, etc. (so no prefix ts_, sta_ etc.) This seems to lead to different issues (see https://github.com/52North/sensorweby/issues/20). Could it be that R automatically converts ID's consisting of only numbers to numeric and subsequentlly handels these ID's differently?

**Comment by autermann** [comment]
> Could it be that R automatically converts ID's consisting of only numbers to numeric and subsequentlly handels these ID's differently?

The problem is a slightly different one. See https://github.com/52North/sensorweby/pull/23
